export const IP = 'http://194.233.79.69:92/';
// export const IP = 'https://getmovers.co.uk';
// export const IP = 'https://getmovers.katashempstead.com';
export const URLS = {
  reimbursement_url: `${IP}/ReimbursementRequest/`,
  leave_base_url: `${IP}/LeaveRequest/`,
  leave_doc_url: `${IP}/LeaveRequestbyuser/`,
  loan_base_url: `${IP}/loan/`,
  advance_base_url: `${IP}/AdvancesSelfServiceController/`,
  wfh_base_url: `${IP}/WFHRequest/`,
  Atd_base_url: `${IP}/AtdRequestController/`,
  complaint_base_url: `${IP}/ComplaintController/`,
  event_calender_base_url: `${IP}/EventCalendar/`,
  task_management_url: `${IP}/TaskMangerController/`,
  todo_base_url: `${IP}/tbl_SS_TodoController/`,
  designation_base_url: `${IP}/Designation/`,
  overtime_base_url: `${IP}/SelfServiceOverTime/`,
  strike_letter_base_url: `${IP}/StrikeLetterController/`,
  emp_letters_base_url: `${IP}/EmpolyeeLatterController/`,
  letter_types_base_url: `${IP}/LetterFormatController/`,
  main_url: `${IP}/`,
  // login: `${IP}/token`,
  auth: {
    //http://194.233.79.69:92/ReimbursementRequest/FinancialYear/?_companyID=8
   // http://194.233.79.69:92/ReimbursementRequest/GetValues?fmonth=November,2024&finyear=2024-2025
    reinbursement: 'GetReimbursements/',
    reinbursementType: 'GetReimbursementTypes/',
    reinbursement_post: 'Save',
    financialYear: 'FinancialYearBYYear/',
    requestId: 'GetValues',
    reimbursementDetails: 'GetById/',
    login: 'token',
    leave_list: 'getLeaves/',
    leavetype_list: 'Loann/getLeaveCategory',
    leave_list_by_category: 'getLeavesByCategory/',
    leave_post: 'saveLeave',
    leave_doc_post: 'saveDocs/',
    loan_list: 'getLoanforselfservice/',
    loan_post: 'SaveLoan/',
    advance_list: 'getAdvancesSelfServiceController/',
    advance_post: 'SaveAdvance',
    wfh_list: 'GetWFHRequest/',
    wfh_post: 'Save',
    wfh_category: 'GetWFHCategory',
    complaint_list: 'GetComplaintsOfEmoployee/',
    complaint_post: 'SaveComplaint',
    atd_correction_post: 'SaveReqDetail',
    atd_correction_list: 'GetCorrectionRequest',
    task_management_list: 'gettaskemployee/',
    task_management_By_Id: 'getsingletaskcategoryyyy/',
    task_management_update_status: 'updatestatus',
    task_management_update_remarks: 'AddEmpolyeeRemark',
    todo_list: 'GetAllTask/',
    todo_list_By_Status: 'GetAllTaskByStatus/',
    todo_list_By_Date: 'GetAllTaskByStatusandDate/',
    todo_post: 'AddUpdateTodo',
    event_calender_list: 'GetEvents/',
    event_calender_list_By_Date: 'GetEventswithDate/',
    event_calender_post: 'Save/',
    event_calender_repetation_type_list: 'GetEventsRepeatitionType',
    event_calender_notification_type_list: 'GetEventsNotificationType',
    designation_list: 'departmentsListofEmp',
    total_employees: 'getTotEmployees/',
    overtime_list: 'getOverTimeRequests/',
    strike_letter: 'GetissueStrikeLatter/',
    strike_letter_details: 'getStrikelatter/',
    emp_letters: 'GetissueLatter/',
    emp_letters_detail: 'getlatter/',
    letter_types: 'AllFormatTypes',
    get_term: 'getUserTerms',
    get_contactUs: 'contactUsInfo',
    get_tracking: 'driverOrderLocation',
    delete_account: 'deleteAccount',
  },
  app: {
    post_fillstore: 'fillStore/',
    get_orderlist: 'OrderList',
    get_order_details: 'OrderDetails',
    driver_review: 'driverReview',
    place_hour_order: 'placeOrder',
  },
  chat: {
    get_chat_messages: 'chat/messages/',
    get_latest_message: 'chat/get-new-messages/',
    get_conservation: 'chat/conversations',
    send_message: 'chat/insert-message',
    create_conservation: 'chat/create-conversation',
  },
  notification: {
    get_notification: 'customerNotification',
    read_notification: 'notificationRead',
  },
};
